import PDFDocument from 'pdfkit';
import { PrismaClient } from '@prisma/client';
import { Readable } from 'stream';

const prisma = new PrismaClient();

interface PDFGenerationOptions {
  assessmentId: string;
  userId: string;
}

/**
 * PDFGeneratorService
 *
 * Generates professional PDF reports for completed assessments including:
 * - Executive summary
 * - Overall scores
 * - Module breakdown
 * - Risk analysis
 * - Recommendations
 * - 30-60-90 day action plan
 */
export class PDFGeneratorService {
  /**
   * Generate PDF report for an assessment
   * Returns a readable stream of the PDF document
   */
  async generateReport(options: PDFGenerationOptions): Promise<Readable> {
    const { assessmentId, userId } = options;

    // Fetch assessment with all related data
    const assessment = await prisma.assessment.findFirst({
      where: {
        id: assessmentId,
        userId,
        status: 'COMPLETED',
      },
      include: {
        businessProfile: true,
        moduleScores: {
          include: {
            module: true,
          },
          orderBy: {
            module: {
              orderIndex: 'asc',
            },
          },
        },
        riskFlags: {
          orderBy: [
            { riskLevel: 'desc' },
            { createdAt: 'asc' },
          ],
        },
        recommendations: {
          include: {
            module: {
              select: {
                name: true,
                category: true,
              },
            },
          },
          orderBy: [
            { priority: 'asc' },
            { createdAt: 'asc' },
          ],
        },
        _count: {
          select: {
            responses: true,
          },
        },
      },
    });

    if (!assessment) {
      throw new Error('Assessment not found or not completed');
    }

    // Create PDF document
    const doc = new PDFDocument({
      size: 'A4',
      margins: {
        top: 50,
        bottom: 50,
        left: 50,
        right: 50,
      },
      info: {
        Title: `Digital Readiness Assessment - ${assessment.businessProfile?.businessName}`,
        Author: 'DRLTAS',
        Subject: 'Business Digital Readiness Assessment Report',
        Keywords: 'digital readiness, business assessment, exit planning',
      },
    });

    // Generate report sections
    this.addCoverPage(doc, assessment);
    this.addExecutiveSummary(doc, assessment);
    this.addScoreOverview(doc, assessment);
    this.addModuleBreakdown(doc, assessment);
    this.addRiskAnalysis(doc, assessment);
    this.addRecommendations(doc, assessment);
    this.addActionPlan(doc, assessment);
    this.addFooter(doc);

    // Finalize PDF
    doc.end();

    return doc;
  }

  /**
   * Cover Page
   */
  private addCoverPage(doc: PDFKit.PDFDocument, assessment: any): void {
    const overallScore = Math.round(assessment.overallScore || 0);

    // Title
    doc
      .fontSize(32)
      .font('Helvetica-Bold')
      .text('Digital Readiness &', { align: 'center' })
      .text('Legacy Transfer Assessment', { align: 'center' });

    doc.moveDown(2);

    // Business Name
    doc
      .fontSize(24)
      .font('Helvetica')
      .text(assessment.businessProfile?.businessName || 'Business Assessment', {
        align: 'center',
      });

    doc.moveDown(3);

    // Overall Score Box
    doc
      .fontSize(16)
      .font('Helvetica')
      .text('Overall Readiness Score', { align: 'center' });

    doc.moveDown(0.5);

    doc
      .fontSize(72)
      .font('Helvetica-Bold')
      .fillColor(this.getScoreColor(overallScore))
      .text(`${overallScore}`, { align: 'center' })
      .fillColor('#000000');

    doc.moveDown(0.5);

    doc
      .fontSize(20)
      .font('Helvetica')
      .text(this.getScoreLabel(overallScore), { align: 'center' });

    doc.moveDown(4);

    // Date
    doc
      .fontSize(12)
      .font('Helvetica')
      .fillColor('#666666')
      .text(
        `Assessment Completed: ${new Date(assessment.completedAt).toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'long',
          day: 'numeric',
        })}`,
        { align: 'center' }
      )
      .fillColor('#000000');

    doc.moveDown(1);

    doc
      .fontSize(10)
      .fillColor('#999999')
      .text('Generated by DRLTAS', { align: 'center' })
      .text('Digital Readiness & Legacy Transfer Audit System', { align: 'center' })
      .fillColor('#000000');

    doc.addPage();
  }

  /**
   * Executive Summary
   */
  private addExecutiveSummary(doc: PDFKit.PDFDocument, assessment: any): void {
    this.addSectionHeader(doc, 'Executive Summary');

    const overallScore = Math.round(assessment.overallScore || 0);
    const digitalScore = Math.round(assessment.digitalScore || 0);
    const legacyScore = Math.round(assessment.legacyScore || 0);
    const criticalRisks = assessment.riskFlags?.filter((r: any) => r.riskLevel === 'CRITICAL')
      .length || 0;
    const immediateRecs = assessment.recommendations?.filter(
      (r: any) => r.priority === 'IMMEDIATE'
    ).length || 0;

    doc.fontSize(11).font('Helvetica');

    // Business Profile
    doc
      .font('Helvetica-Bold')
      .text('Business Profile', { underline: true })
      .font('Helvetica');
    doc.text(`Industry: ${assessment.businessProfile?.industry || 'N/A'}`);
    doc.text(`Business Size: ${assessment.businessProfile?.businessSize || 'N/A'}`);
    doc.text(`Growth Stage: ${assessment.businessProfile?.growthStage || 'N/A'}`);

    doc.moveDown();

    // Overall Assessment
    doc
      .font('Helvetica-Bold')
      .text('Overall Readiness Assessment', { underline: true })
      .font('Helvetica');

    doc.text(
      `Your business achieved an overall readiness score of ${overallScore}/100, indicating ${this.getScoreLabel(
        overallScore
      ).toLowerCase()} preparation for digital transformation and business transfer.`
    );

    doc.moveDown();

    doc.text(`Digital Readiness: ${digitalScore}/100 - ${this.getScoreLabel(digitalScore)}`);
    doc.text(
      `Legacy Transfer Readiness: ${legacyScore}/100 - ${this.getScoreLabel(legacyScore)}`
    );

    doc.moveDown();

    // Key Findings
    doc
      .font('Helvetica-Bold')
      .text('Key Findings', { underline: true })
      .font('Helvetica');

    if (criticalRisks > 0) {
      doc
        .fillColor('#DC2626')
        .text(`• ${criticalRisks} CRITICAL risk(s) identified requiring immediate attention`)
        .fillColor('#000000');
    }

    if (immediateRecs > 0) {
      doc.text(`• ${immediateRecs} immediate priority recommendation(s) (0-30 day timeline)`);
    }

    doc.text(`• ${assessment.moduleScores?.length || 0} modules assessed`);
    doc.text(`• ${assessment._count?.responses || 0} questions answered`);

    doc.moveDown();

    // Recommendation Summary
    const gap = Math.abs(digitalScore - legacyScore);
    if (gap > 30) {
      doc
        .font('Helvetica-Bold')
        .text('Critical Gap Identified', { underline: true })
        .font('Helvetica');
      doc.text(
        `Significant imbalance detected between Digital Readiness (${digitalScore}) and Legacy Transfer Readiness (${legacyScore}). We recommend focusing improvement efforts on the lower-scoring category to create a more balanced readiness profile.`
      );
      doc.moveDown();
    }

    if (overallScore < 50) {
      doc
        .font('Helvetica-Bold')
        .fillColor('#DC2626')
        .text('Immediate Action Required', { underline: true })
        .font('Helvetica')
        .fillColor('#000000');
      doc.text(
        'Your current readiness score indicates significant preparation is needed before pursuing a business sale or major digital transformation. We recommend engaging with business advisors and prioritizing the immediate recommendations in this report.'
      );
    } else if (overallScore < 70) {
      doc
        .font('Helvetica-Bold')
        .text('Improvement Opportunities', { underline: true })
        .font('Helvetica');
      doc.text(
        'Your business shows moderate readiness with clear opportunities for improvement. Focus on the high-priority recommendations to increase valuation and reduce transaction risk.'
      );
    } else {
      doc
        .font('Helvetica-Bold')
        .fillColor('#059669')
        .text('Strong Foundation', { underline: true })
        .font('Helvetica')
        .fillColor('#000000');
      doc.text(
        'Your business demonstrates strong readiness for digital transformation and business transfer. Continue with the recommendations to optimize for maximum valuation.'
      );
    }

    doc.addPage();
  }

  /**
   * Score Overview
   */
  private addScoreOverview(doc: PDFKit.PDFDocument, assessment: any): void {
    this.addSectionHeader(doc, 'Score Overview');

    const overallScore = Math.round(assessment.overallScore || 0);
    const digitalScore = Math.round(assessment.digitalScore || 0);
    const legacyScore = Math.round(assessment.legacyScore || 0);

    doc.fontSize(11).font('Helvetica');

    // Overall Score
    doc.font('Helvetica-Bold').fontSize(14).text('Overall Readiness Score');
    doc.fontSize(11).font('Helvetica');
    this.addProgressBar(doc, overallScore, `${overallScore}/100`);
    doc.moveDown();

    // Digital Readiness
    doc.font('Helvetica-Bold').fontSize(14).text('Digital Readiness');
    doc.fontSize(11).font('Helvetica');
    doc.text(
      'Measures your digital systems, online presence, and technology infrastructure readiness.'
    );
    this.addProgressBar(doc, digitalScore, `${digitalScore}/100`);
    doc.moveDown();

    // Legacy Transfer Readiness
    doc.font('Helvetica-Bold').fontSize(14).text('Legacy Transfer Readiness');
    doc.fontSize(11).font('Helvetica');
    doc.text(
      'Evaluates operational processes, succession planning, and transferability to new ownership.'
    );
    this.addProgressBar(doc, legacyScore, `${legacyScore}/100`);
    doc.moveDown();

    // Score Interpretation Guide
    doc.moveDown();
    doc.font('Helvetica-Bold').text('Score Interpretation Guide', { underline: true });
    doc.font('Helvetica');
    doc.fillColor('#059669').text('80-100: Excellent - Ready for transaction').fillColor('#000000');
    doc.fillColor('#2563EB').text('60-79: Good - Minor improvements needed').fillColor('#000000');
    doc
      .fillColor('#D97706')
      .text('40-59: Fair - Significant preparation required')
      .fillColor('#000000');
    doc
      .fillColor('#DC2626')
      .text('0-39: Needs Improvement - Major gaps identified')
      .fillColor('#000000');

    doc.addPage();
  }

  /**
   * Module Breakdown
   */
  private addModuleBreakdown(doc: PDFKit.PDFDocument, assessment: any): void {
    this.addSectionHeader(doc, 'Module Breakdown');

    doc.fontSize(10).font('Helvetica');
    doc.text('Detailed scores across all 10 assessment modules:', { continued: false });
    doc.moveDown();

    assessment.moduleScores?.forEach((moduleScore: any, index: number) => {
      const score = Math.round(moduleScore.score);

      // Module name and category
      doc
        .font('Helvetica-Bold')
        .fontSize(12)
        .text(`${index + 1}. ${moduleScore.module.name}`);

      doc
        .font('Helvetica')
        .fontSize(9)
        .fillColor('#666666')
        .text(this.getModuleCategoryLabel(moduleScore.module.category))
        .fillColor('#000000');

      doc.fontSize(10);

      // Progress bar
      this.addProgressBar(doc, score, `${score}/100`);

      doc.moveDown(0.5);

      // Add page break if needed (every 3-4 modules)
      if (index === 4 && assessment.moduleScores.length > 5) {
        doc.addPage();
        this.addSectionHeader(doc, 'Module Breakdown (continued)');
        doc.fontSize(10).font('Helvetica');
      }
    });

    doc.addPage();
  }

  /**
   * Risk Analysis
   */
  private addRiskAnalysis(doc: PDFKit.PDFDocument, assessment: any): void {
    this.addSectionHeader(doc, 'Risk Analysis');

    const risks = assessment.riskFlags || [];

    if (risks.length === 0) {
      doc
        .fontSize(11)
        .font('Helvetica')
        .fillColor('#059669')
        .text('No significant risks identified. Excellent work!')
        .fillColor('#000000');
      doc.addPage();
      return;
    }

    doc.fontSize(10).font('Helvetica');
    doc.text(
      `${risks.length} risk(s) identified based on your assessment responses. Risks are categorized by severity and include mitigation guidance.`
    );
    doc.moveDown();

    risks.forEach((risk: any, index: number) => {
      // Risk header with severity badge
      const severityColor = this.getRiskColor(risk.riskLevel);
      doc
        .font('Helvetica-Bold')
        .fontSize(12)
        .fillColor(severityColor)
        .text(`[${risk.riskLevel}] `, { continued: true })
        .fillColor('#000000')
        .text(risk.title, { continued: false });

      doc
        .font('Helvetica')
        .fontSize(9)
        .fillColor('#666666')
        .text(`Category: ${risk.category}`)
        .fillColor('#000000');

      doc.fontSize(10).moveDown(0.3);

      // Description
      doc.font('Helvetica').text(risk.description);
      doc.moveDown(0.3);

      // Impact
      doc.font('Helvetica-Bold').text('Impact: ', { continued: true });
      doc.font('Helvetica').text(risk.impact, { continued: false });
      doc.moveDown(0.3);

      // Mitigation
      if (risk.mitigation) {
        doc.font('Helvetica-Bold').text('Mitigation: ', { continued: true });
        doc.font('Helvetica').text(risk.mitigation, { continued: false });
      }

      doc.moveDown();

      // Page break if needed (every 2-3 risks)
      if (index < risks.length - 1 && (index + 1) % 2 === 0) {
        doc.addPage();
        this.addSectionHeader(doc, 'Risk Analysis (continued)');
        doc.fontSize(10).font('Helvetica');
      }
    });

    doc.addPage();
  }

  /**
   * Recommendations
   */
  private addRecommendations(doc: PDFKit.PDFDocument, assessment: any): void {
    this.addSectionHeader(doc, 'Recommendations');

    const recommendations = assessment.recommendations || [];

    if (recommendations.length === 0) {
      doc.fontSize(11).font('Helvetica').text('No specific recommendations at this time.');
      doc.addPage();
      return;
    }

    doc.fontSize(10).font('Helvetica');
    doc.text(
      `${recommendations.length} recommendation(s) tailored to your assessment results. Recommendations are prioritized by urgency and include implementation guidance.`
    );
    doc.moveDown();

    recommendations.forEach((rec: any, index: number) => {
      // Recommendation header with priority
      const priorityColor = this.getPriorityColor(rec.priority);
      doc
        .font('Helvetica-Bold')
        .fontSize(12)
        .fillColor(priorityColor)
        .text(`[${this.getPriorityLabel(rec.priority)}] `, { continued: true })
        .fillColor('#000000')
        .text(rec.title, { continued: false });

      if (rec.module) {
        doc
          .font('Helvetica')
          .fontSize(9)
          .fillColor('#666666')
          .text(`Module: ${rec.module.name}`)
          .fillColor('#000000');
      }

      doc.fontSize(10).moveDown(0.3);

      // Description
      doc.font('Helvetica').text(rec.description);
      doc.moveDown(0.3);

      // Cost and Timeframe
      if (rec.estimatedCost || rec.estimatedTimeframe) {
        doc.font('Helvetica-Bold').text('Investment: ', { continued: true });
        doc
          .font('Helvetica')
          .text(
            `${rec.estimatedCost || 'TBD'} over ${rec.estimatedTimeframe || 'TBD'}`,
            { continued: false }
          );
        doc.moveDown(0.3);
      }

      // Expected Impact
      doc.font('Helvetica-Bold').text('Expected Impact: ', { continued: true });
      doc.font('Helvetica').text(rec.expectedImpact, { continued: false });
      doc.moveDown(0.3);

      // Valuation Impact
      if (rec.valuationImpact) {
        doc.font('Helvetica-Bold').text('Valuation Impact: ', { continued: true });
        doc.font('Helvetica').text(rec.valuationImpact, { continued: false });
        doc.moveDown(0.3);
      }

      doc.moveDown(0.5);

      // Page break if needed
      if (index < recommendations.length - 1 && (index + 1) % 2 === 0) {
        doc.addPage();
        this.addSectionHeader(doc, 'Recommendations (continued)');
        doc.fontSize(10).font('Helvetica');
      }
    });

    doc.addPage();
  }

  /**
   * 30-60-90 Day Action Plan
   */
  private addActionPlan(doc: PDFKit.PDFDocument, assessment: any): void {
    this.addSectionHeader(doc, '30-60-90 Day Action Plan');

    const immediateRecs = assessment.recommendations?.filter(
      (r: any) => r.priority === 'IMMEDIATE'
    ) || [];
    const shortTermRecs = assessment.recommendations?.filter(
      (r: any) => r.priority === 'SHORT_TERM'
    ) || [];

    doc.fontSize(10).font('Helvetica');
    doc.text(
      'Prioritized action plan based on your assessment results. Focus on immediate priorities first for maximum impact.'
    );
    doc.moveDown();

    // 0-30 Days (Immediate)
    doc
      .font('Helvetica-Bold')
      .fontSize(12)
      .fillColor('#DC2626')
      .text('First 30 Days (Immediate Priorities)')
      .fillColor('#000000');
    doc.fontSize(10).font('Helvetica');

    if (immediateRecs.length > 0) {
      immediateRecs.forEach((rec: any, index: number) => {
        doc.text(`${index + 1}. ${rec.title}`);
        if (rec.estimatedCost) {
          doc.fontSize(9).fillColor('#666666').text(`   Cost: ${rec.estimatedCost}`);
        }
        if (rec.estimatedTimeframe) {
          doc.text(`   Timeframe: ${rec.estimatedTimeframe}`).fillColor('#000000');
        }
        doc.fontSize(10).moveDown(0.3);
      });
    } else {
      doc.text('No immediate priorities identified.');
    }

    doc.moveDown();

    // 30-90 Days (Short-term)
    doc
      .font('Helvetica-Bold')
      .fontSize(12)
      .fillColor('#D97706')
      .text('Next 30-90 Days (Short-Term Priorities)')
      .fillColor('#000000');
    doc.fontSize(10).font('Helvetica');

    if (shortTermRecs.length > 0) {
      shortTermRecs.slice(0, 5).forEach((rec: any, index: number) => {
        doc.text(`${index + 1}. ${rec.title}`);
        if (rec.estimatedCost) {
          doc.fontSize(9).fillColor('#666666').text(`   Cost: ${rec.estimatedCost}`);
        }
        if (rec.estimatedTimeframe) {
          doc.text(`   Timeframe: ${rec.estimatedTimeframe}`).fillColor('#000000');
        }
        doc.fontSize(10).moveDown(0.3);
      });
    } else {
      doc.text('No short-term priorities identified.');
    }

    doc.moveDown();

    // Next Steps
    doc
      .font('Helvetica-Bold')
      .fontSize(12)
      .text('Recommended Next Steps')
      .font('Helvetica')
      .fontSize(10);

    doc.text('1. Review all identified risks and determine mitigation priorities');
    doc.text('2. Allocate budget and resources for immediate recommendations');
    doc.text('3. Assign ownership and timelines for each action item');
    doc.text('4. Re-assess in 90 days to measure progress');
    doc.text('5. Consult with business advisors for complex recommendations');

    doc.addPage();
  }

  /**
   * Footer / Disclaimer
   */
  private addFooter(doc: PDFKit.PDFDocument): void {
    doc.fontSize(10).font('Helvetica-Bold').text('About This Report', { underline: true });

    doc.fontSize(9).font('Helvetica');
    doc.text(
      'This Digital Readiness & Legacy Transfer Assessment Report is generated by DRLTAS based on your responses to a comprehensive questionnaire covering 10 key business modules.'
    );
    doc.moveDown(0.5);

    doc.text(
      'This report provides general guidance and should not be considered as legal, financial, or professional advice. For specific recommendations tailored to your unique situation, we recommend consulting with qualified business advisors, M&A professionals, and industry experts.'
    );
    doc.moveDown(0.5);

    doc.text(
      'The scores and recommendations are based on industry best practices and common patterns observed in successful business exits and digital transformations. Actual results may vary based on your specific circumstances, market conditions, and execution quality.'
    );
    doc.moveDown(1);

    doc
      .fontSize(8)
      .fillColor('#999999')
      .text('© 2025 DRLTAS. All rights reserved.', { align: 'center' })
      .text(`Report Generated: ${new Date().toLocaleDateString()}`, { align: 'center' })
      .fillColor('#000000');
  }

  // Helper methods

  private addSectionHeader(doc: PDFKit.PDFDocument, title: string): void {
    doc
      .fontSize(18)
      .font('Helvetica-Bold')
      .fillColor('#1F2937')
      .text(title)
      .fillColor('#000000')
      .moveDown(0.5);
  }

  private addProgressBar(doc: PDFKit.PDFDocument, percentage: number, label: string): void {
    const barWidth = 400;
    const filledWidth = (barWidth * percentage) / 100;

    // Draw empty bar
    doc
      .rect(doc.x, doc.y, barWidth, 20)
      .lineWidth(1)
      .stroke('#CCCCCC');

    // Draw filled bar
    doc
      .rect(doc.x, doc.y, filledWidth, 20)
      .fillAndStroke(this.getScoreColor(percentage), '#CCCCCC');

    // Add label
    doc
      .fontSize(10)
      .fillColor('#000000')
      .text(label, doc.x + barWidth + 10, doc.y - 15);

    doc.moveDown(1.5);
  }

  private getScoreColor(score: number): string {
    if (score >= 80) return '#059669'; // Green
    if (score >= 60) return '#2563EB'; // Blue
    if (score >= 40) return '#D97706'; // Yellow
    return '#DC2626'; // Red
  }

  private getScoreLabel(score: number): string {
    if (score >= 80) return 'Excellent';
    if (score >= 60) return 'Good';
    if (score >= 40) return 'Fair';
    return 'Needs Improvement';
  }

  private getRiskColor(level: string): string {
    switch (level) {
      case 'CRITICAL':
        return '#DC2626';
      case 'HIGH':
        return '#EA580C';
      case 'MEDIUM':
        return '#D97706';
      case 'LOW':
        return '#2563EB';
      default:
        return '#000000';
    }
  }

  private getPriorityColor(priority: string): string {
    switch (priority) {
      case 'IMMEDIATE':
        return '#DC2626';
      case 'SHORT_TERM':
        return '#EA580C';
      case 'MEDIUM_TERM':
        return '#D97706';
      case 'LONG_TERM':
        return '#2563EB';
      default:
        return '#000000';
    }
  }

  private getPriorityLabel(priority: string): string {
    switch (priority) {
      case 'IMMEDIATE':
        return '0-30 DAYS';
      case 'SHORT_TERM':
        return '30-90 DAYS';
      case 'MEDIUM_TERM':
        return '90-180 DAYS';
      case 'LONG_TERM':
        return '180+ DAYS';
      default:
        return priority;
    }
  }

  private getModuleCategoryLabel(category: string): string {
    const labels: Record<string, string> = {
      DIGITAL_PRESENCE: 'Digital Presence & Marketing',
      PROCESS_ORGANIZATION: 'Process & Organization',
      CRM_ERP_SYSTEMS: 'CRM & ERP Systems',
      FINANCIAL_SYSTEMS: 'Financial Systems & Controls',
      TECH_INFRASTRUCTURE: 'Technology Infrastructure',
      DATA_SECURITY: 'Data Security & Compliance',
      PEOPLE_TRAINING: 'People & Training',
      CUSTOMER_EXPERIENCE: 'Customer Experience',
      SCALABILITY: 'Scalability & Growth',
      SUCCESSION_READINESS: 'Succession & Transfer Readiness',
    };
    return labels[category] || category;
  }
}
